### ISSUE TITLE
Error: error while reading from input stream

### ISSUE THREAD

**Issue by lijiarui** [zixia/wechaty-blinder#1]
when run `npm run start` when someone send a pic, it will get the following error.

```shell
Error: error while reading from input stream
    at Image.src (/Users/jiaruili/git/wechaty-blinder/node_modules/canvas/lib/image.js:30:17)
    at Promise (/Users/jiaruili/git/wechaty-blinder/node_modules/canvas/index.js:32:15)
    at Promise (<anonymous>)
    at loadImage (/Users/jiaruili/git/wechaty-blinder/node_modules/canvas/index.js:21:10)
    at Object.<anonymous> (/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/src/misc.ts:108:23)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/wechaty-blinder/node_modules/facenet/dist/src/misc.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/dist/src/misc.js:3:12)
    at Object.loadImage (/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/dist/src/misc.js:103:12)
    at AlignmentCache.<anonymous> (/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/src/cache/alignment-cache.ts:87:15)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/wechaty-blinder/node_modules/facenet/dist/src/cache/alignment-cache.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/dist/src/cache/alignment-cache.js:3:12)
    at AlignmentCache.align (/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/dist/src/cache/alignment-cache.js:49:16)
    at FaceBlinder.<anonymous> (/Users/jiaruili/git/wechaty-blinder/node_modules/face-blinder/src/face-blinder.ts:107:48)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/wechaty-blinder/node_modules/face-blinder/dist/src/face-blinder.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/wechaty-blinder/node_modules/face-blinder/dist/src/face-blinder.js:3:12)
    at FaceBlinder.see (/Users/jiaruili/git/wechaty-blinder/node_modules/face-blinder/dist/src/face-blinder.js:80:16)
    at Wechaty.<anonymous> (/Users/jiaruili/git/wechaty-blinder/src/listeners/message.ts:135:34)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/wechaty-blinder/src/listeners/message.ts:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/wechaty-blinder/src/listeners/message.ts:3:12)
    at Wechaty.onImage (/Users/jiaruili/git/wechaty-blinder/src/listeners/message.ts:94:12)
    at Wechaty.<anonymous> (/Users/jiaruili/git/wechaty-blinder/src/listeners/message.ts:126:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jiaruili/git/wechaty-blinder/src/listeners/message.ts:4:58)
    at <anonymous>
```
I can save pic as follows:
```shell
➜  wechaty-blinder git:(master) cd workdir
➜  workdir git:(master) ls -l
total 488
-rw-r--r--  1 jiaruili  staff  86634 Oct 10 12:44 3077304179069206016.jpg
-rw-r--r--  1 jiaruili  staff  47053 Oct 10 12:44 8008587046769448672.jpg
-rw-r--r--  1 jiaruili  staff  85912 Oct 10 12:59 8639235338090727085.jpg
-rw-r--r--  1 jiaruili  staff  22262 Oct 10 12:44 李卓桓.jpg
```

**Comment by zixia** [comment]
Sorry I can not reproduce it.

**Comment by lijiarui** [comment]
I thought I found the result, when it is `png` file, it can send image, but if it is `jpg` file, it cannot send image.

The following is the result, just now I send 21 png file as follows.
```
➜  workdir git:(master) ls
0o4u37tas4.png          3766075240201906553.jpg 8485238360586070615.jpg jl5q1qg19ib.png
1238955347038503297.jpg 3955854207134803117.jpg 8639235338090727085.jpg k3d5if2eqy.png
127001582247706535.jpg  3jadxiddl.png           9210695144008939159.jpg m9hmfo4zvxb.png
1305176626530029863.jpg 4747266113411120701.jpg ai8v6yhh63.png          mpwg3d7eli.png
1587842566950035718.jpg 56537725246728113.jpg   ba19te82u2.png          oclvjiacm5.png
2421108861545951218.jpg 6eodoh6irhf.png         bdoqg1hbjjw.png         u47kvzpl38.png
2751827357367712076.jpg 7192926182297211031.jpg cm7xjn8h1e.png          y5vkvwdngo.png
2848563649473592772.jpg 7657527718110707192.jpg e7ylds0plwt.png         y9rqkz7yqzb.png
3009949715164427330.jpg 776178048346768476.jpg  eculg6las8l.png         zqhs9b1q2wq.png
3077304179069206016.jpg 7dszaacpp8.png          icul5nffrvf.png         李卓桓.jpg
3275153150534095783.jpg 8008587046769448672.jpg j87phf0pbmg.png
```

But I have an question, how to get png file?  When I save a pic as png and send it, it will save to a jpg file, and get the result.

**Comment by lijiarui** [comment]
Also，I found the way I change the file format is wrong.
Firstly, I change the format just by changing suffix of the filename(changing `.jpg` to `.png`)， it not works, then I use photoshop change jpg file to png file, and then, it works and cannot catch error.

I believe this is because the file format, but cannot get a good solution.

**Comment by lijiarui** [comment]
Solution:
see  https://github.com/Automattic/node-canvas/issues/110
```
brew install libjpeg
```

What's more, only when all brew install done then run `npm install` it works. see https://github.com/Automattic/node-canvas/issues/364


I did this by `brew install libjpeg` , it doesn't work.
Than I remove nodemoluse and `npm install` again, it works...

**Comment by zixia** [comment]
Good catch.

See:
https://github.com/zixia/node-facenet/blob/4e0edcffce5a9bc975e226348902b609e35b1a94/.travis.yml#L19
