### ISSUE TITLE
Cannot install when update the repo

### ISSUE THREAD

**Issue by lijiarui** [zixia/wechaty-blinder#29]
I have installed all related packages, then try npm install, I get the following error
```shell
Collecting lazy-object-proxy (from astroid>=1.5.1->pylint->-r requirements.txt (line 4))
  Using cached lazy-object-proxy-1.3.1.tar.gz
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow from https://pypi.python.org/packages/a9/72/4f573aa9d41e740e79594a0bd949288f2eb4286f453cf560799eaa29d024/tensorflow-1.4.0-cp36-cp36m-macosx_10_11_x86_64.whl#md5=3a3045234575ee3bc77c7d2a70da39ea (from -r requirements.txt (line 9)):
        Expected md5 3a3045234575ee3bc77c7d2a70da39ea
             Got        4ad23bb8a448a855a68cb59d870236d8
```

full log as follows
```
> facenet@0.7.13 venv /Users/jiaruili/git/rui/wechaty-blinder/node_modules/facenet
> python3 -m venv python3 && . python3/bin/activate && pip3 install -r requirements.txt

Collecting flake8 (from -r requirements.txt (line 1))
  Using cached flake8-3.5.0-py2.py3-none-any.whl
Collecting mypy (from -r requirements.txt (line 2))
  Using cached mypy-0.550-py3-none-any.whl
Collecting pillow (from -r requirements.txt (line 3))
  Using cached Pillow-4.3.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pylint (from -r requirements.txt (line 4))
  Using cached pylint-1.7.4-py2.py3-none-any.whl
Collecting pytest (from -r requirements.txt (line 5))
  Using cached pytest-3.2.5-py2.py3-none-any.whl
Collecting opencv-python (from -r requirements.txt (line 6))
  Using cached opencv_python-3.3.0.10-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scipy (from -r requirements.txt (line 7))
  Using cached scipy-1.0.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting sklearn (from -r requirements.txt (line 8))
  Using cached sklearn-0.0.tar.gz
Collecting tensorflow (from -r requirements.txt (line 9))
  Downloading tensorflow-1.4.0-cp36-cp36m-macosx_10_11_x86_64.whl (39.3MB)
    0% |▎                               | 368kB 44kB/s eta 0:14:38
Collecting typing (from -r requirements.txt (line 10))
  Using cached typing-3.6.2-py3-none-any.whl
Collecting wheel (from -r requirements.txt (line 11))
  Using cached wheel-0.30.0-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8->-r requirements.txt (line 1))
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8->-r requirements.txt (line 1))
  Using cached mccabe-0.6.1-py2.py3-none-any.whl
Collecting pyflakes<1.7.0,>=1.5.0 (from flake8->-r requirements.txt (line 1))
  Using cached pyflakes-1.6.0-py2.py3-none-any.whl
Collecting psutil<5.5.0,>=5.4.0 (from mypy->-r requirements.txt (line 2))
  Using cached psutil-5.4.1.tar.gz
Collecting typed-ast<1.2.0,>=1.1.0 (from mypy->-r requirements.txt (line 2))
  Using cached typed_ast-1.1.0-cp36-cp36m-macosx_10_11_x86_64.whl
Collecting olefile (from pillow->-r requirements.txt (line 3))
  Using cached olefile-0.44.zip
Collecting astroid>=1.5.1 (from pylint->-r requirements.txt (line 4))
  Using cached astroid-1.5.3-py2.py3-none-any.whl
Collecting isort>=4.2.5 (from pylint->-r requirements.txt (line 4))
  Using cached isort-4.2.15-py2.py3-none-any.whl
Collecting six (from pylint->-r requirements.txt (line 4))
  Using cached six-1.11.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./python3/lib/python3.6/site-packages (from pytest->-r requirements.txt (line 5))
Collecting py>=1.4.33 (from pytest->-r requirements.txt (line 5))
  Using cached py-1.5.2-py2.py3-none-any.whl
Collecting numpy>=1.11.1 (from opencv-python->-r requirements.txt (line 6))
  Using cached numpy-1.13.3-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scikit-learn (from sklearn->-r requirements.txt (line 8))
  Using cached scikit_learn-0.19.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting lazy-object-proxy (from astroid>=1.5.1->pylint->-r requirements.txt (line 4))
  Using cached lazy-object-proxy-1.3.1.tar.gz
Collecting wrapt (from astroid>=1.5.1->pylint->-r requirements.txt (line 4))
  Using cached wrapt-1.10.11.tar.gz
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    tensorflow from https://pypi.python.org/packages/a9/72/4f573aa9d41e740e79594a0bd949288f2eb4286f453cf560799eaa29d024/tensorflow-1.4.0-cp36-cp36m-macosx_10_11_x86_64.whl#md5=3a3045234575ee3bc77c7d2a70da39ea (from -r requirements.txt (line 9)):
        Expected md5 3a3045234575ee3bc77c7d2a70da39ea
             Got        fabc27675f4218d8e4077aec2f7d1b73
```

**Comment by lijiarui** [comment]
trying the following command
```
cd node_modules/facenet
python3 -m venv python3 && . python3/bin/activate && pip3 install -r requirements.txt
```
will fix, then occure another problem as follows
```
 Error [Errno 2] No such file or directory: '/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/python3/bin/python3' while executing command python setup.py egg_info
Exception:
Traceback (most recent call last):
  File "/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/python3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
  File "/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/python3/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
  File "/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/python3/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
  File "/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/python3/lib/python3.6/site-packages/pip/req/req_set.py", line 634, in _prepare_file
  File "/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/python3/lib/python3.6/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
  File "/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/python3/lib/python3.6/site-packages/pip/req/req_install.py", line 439, in run_egg_info
  File "/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/python3/lib/python3.6/site-packages/pip/utils/__init__.py", line 667, in call_subprocess
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jiaruili/git/wechaty-blinder/node_modules/facenet/python3/bin/python3'
```

**Comment by lijiarui** [comment]
I thought this may because my terminal is in proxy status. When I close the terminal proxy, it fixes.
