### ISSUE TITLE
wechaty-blinder-master

### ISSUE THREAD

**Issue by forconz** [zixia/wechaty-blinder#33]
Windows PowerShell
版权所有 (C) 2016 Microsoft Corporation。保留所有权利。

PS C:\Users\lenovo> cd C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master
PS C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master> cnpm install
\ [0/20] Installing @types/app-root-path@^1.0.0[flash-store@0.1.5 › levelup@github:MeirionHughes/levelup] install levelu
p from git github:MeirionHughes/levelup, may be very slow, please keep patience
\ [10/20] Installing hoek@4.x.x
> facenet@0.7.13 check-version C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master\node_modules\_fac
enet@0.7.13@facenet
> ./bin/check-version.sh

'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! facenet@0.7.13 check-version: `./bin/check-version.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the facenet@0.7.13 check-version script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 | [10/20] Installing error-ex@^1.2.0WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\.npminstall_tarball\_logs\2017-12-25T05_19_06_352Z-debug.log
× Install fail! Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c npm run check-version" error, exit code 1
Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c npm run check-version" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:
74:21)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npminstall version: 3.2.1
npminstall args: D:\Program Files\nodejs\node.exe C:\Users\lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm
install\bin\install.js --china --userconfig=C:\Users\lenovo\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --regi
stry=http://registry.npm.taobao.org
PS C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master>

2017-12-25T05_19_06_352Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'check-version' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose run-script [ 'precheck-version', 'check-version', 'postcheck-version' ]
5 info lifecycle facenet@0.7.13~precheck-version: facenet@0.7.13
6 info lifecycle facenet@0.7.13~check-version: facenet@0.7.13
7 verbose lifecycle facenet@0.7.13~check-version: unsafe-perm in lifecycle true
8 verbose lifecycle facenet@0.7.13~check-version: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master\node_modules\_facenet@0.7.13@facenet\node_modules\.bin;C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master\node_modules\.bin;C:\Users\lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin;C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master\node_modules\.bin;C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master\node_modules\_facenet@0.7.13@facenet\node_modules\.bin;C:\php71\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\ProgramData\Lenovo\ReadyApps;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\MySQL\MySQL Utilities 1.6\;D:\Program Files\TortoiseSVN\bin;D:\Program Files\nodejs\;D:\Program Files\Git\cmd;C:\Users\lenovo\.dnx\bin;C:\Program Files\Java\jdk1.8.0_51\bin;C:\Program Files\Java\jdk1.8.0_51\jre\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\Git\bin;C:\Users\lenovo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\bin;D:\Program Files\Microsoft VS Code\bin;C:\Users\lenovo\AppData\Roaming\npm;D:\Program Files\Docker Toolbox
9 verbose lifecycle facenet@0.7.13~check-version: CWD: C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master\node_modules\_facenet@0.7.13@facenet
10 silly lifecycle facenet@0.7.13~check-version: Args: [ '/d /s /c', './bin/check-version.sh' ]
11 silly lifecycle facenet@0.7.13~check-version: Returned: code: 1  signal: null
12 info lifecycle facenet@0.7.13~check-version: Failed to exec check-version script
13 verbose stack Error: facenet@0.7.13 check-version: `./bin/check-version.sh`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid facenet@0.7.13
15 verbose cwd C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master\node_modules\_facenet@0.7.13@facenet
16 verbose Windows_NT 10.0.14393
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "check-version"
18 verbose node v9.2.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error facenet@0.7.13 check-version: `./bin/check-version.sh`
22 error Exit status 1
23 error Failed at the facenet@0.7.13 check-version script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by forconz** [comment]
PS C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master> cnpm install facenet@0.7.13
/ [0/1] Installing facenet@0.7.13
> facenet@0.7.13 check-version C:\Users\lenovo\Downloads\wechaty-blinder-master\wechaty-blinder-master\node_modules\_fac
enet@0.7.13@facenet
> ./bin/check-version.sh

'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! facenet@0.7.13 check-version: `./bin/check-version.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the facenet@0.7.13 check-version script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\.npminstall_tarball\_logs\2017-12-25T05_22_00_232Z-debug.log
× Install fail! Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c npm run check-version" error, exit code 1
Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c npm run check-version" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:
74:21)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npminstall version: 3.2.1
npminstall args: D:\Program Files\nodejs\node.exe C:\Users\lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm
install\bin\install.js --china --userconfig=C:\Users\lenovo\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --regi
stry=http://registry.npm.taobao.org facenet@0.7.13

**Comment by zixia** [comment]
Sorry, the code base had not been tested under win32 yet, it's Linux/Mac only now.

If you want to make it to support Win32, PR is welcome.
